function viewstudent(){
	n1=document.getElementById("No");
	no=document.getElementById("number1");
	No=document.getElementById("No");
	name=document.getElementById("name");
	email=document.getElementById("email");
	pwd=document.getElementById("pwd");
	dept=document.getElementById("dept");
	course=document.getElementById("course");
	city=document.getElementById("city");
	state=document.getElementById("state");
	phno=document.getElementById("phno");
	No1=document.getElementById("NoR");
	name1=document.getElementById("nameR");
	email1=document.getElementById("emailR");
	pwd1=document.getElementById("pwdR");
	dept1=document.getElementById("deptR");
	course1=document.getElementById("courseR");
	city1=document.getElementById("cityR");
	state1=document.getElementById("stateR");
	phno1=document.getElementById("phnoR");
	if(n1==no){
		No1.value=No;
		name1.value=name;
		email1.value=email;
		pwd1.value=pwd;
		dept1.value=dept;
		course1.value=course;
		city1.value=city;
		state1.value=state;
		phno1.value=phno;
	}
	else{
		No1.value=0;
		name1.value="invalid";
		email1.value="invalid";
		pwd1.value="invalid";
		dept1.value="invalid";
		course1.value="invalid";
		city1.value="invalid";
		state1.value="invalid";
		phno1.value=0;
	}
	
}