function viewfaculty(){
	n1=document.getElementById("fnum");
	no=document.getElementById("number2");
	No=document.getElementById("fnum");
	name=document.getElementById("fname");
	email=document.getElementById("femail");
	pwd=document.getElementById("fpwd");
	dept=document.getElementById("fdept");
	course=document.getElementById("fcourse");
	city=document.getElementById("fcity");
	state=document.getElementById("fstate");
	phno=document.getElementById("fphno");
	No1=document.getElementById("fNoR");
	name1=document.getElementById("fnameR");
	email1=document.getElementById("femailR");
	pwd1=document.getElementById("fpwdR");
	dept1=document.getElementById("fdeptR");
	course1=document.getElementById("fcourseR");
	city1=document.getElementById("fcityR");
	state1=document.getElementById("fstateR");
	phno1=document.getElementById("fphnoR");
	if(n1==no){
		No1.value=No;
		name1.value=name;
		email1.value=email;
		pwd1.value=pwd;
		dept1.value=dept;
		course1.value=course;
		city1.value=city;
		state1.value=state;
		phno1.value=phno;
	}
	else{
		No1.value=0;
		name1.value="invalid";
		email1.value="invalid";
		pwd1.value="invalid";
		dept1.value="invalid";
		course1.value="invalid";
		city1.value="invalid";
		state1.value="invalid";
		phno1.value=0;
	}
	
}